#ifndef ADDDYNAMICLIBTEST_GLOBAL_H
#define ADDDYNAMICLIBTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef Q_OS_WIN
#if defined(ADDDYNAMICLIBTEST_LIBRARY)
#  define ADDDYNAMICLIBTESTSHARED_EXPORT Q_DECL_EXPORT
#elif defined(ADDDYNAMICLIBTEST_STATIC_LIBRARY)
#  define ADDDYNAMICLIBTESTSHARED_EXPORT
#else
#  define ADDDYNAMICLIBTESTSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#  define ADDDYNAMICLIBTESTSHARED_EXPORT
#endif

#endif // ADDDYNAMICLIBTEST_GLOBAL_H
