#ifndef LINKSTATICLIBTEST_GLOBAL_H
#define LINKSTATICLIBTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef Q_OS_WIN
#if defined(LINKSTATICLIBTEST_LIBRARY)
#  define LINKSTATICLIBTESTSHARED_EXPORT Q_DECL_EXPORT
#elif defined(LINKSTATICLIBTEST_STATIC_LIBRARY)
#  define LINKSTATICLIBTESTSHARED_EXPORT
#else
#  define LINKSTATICLIBTESTSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#  define LINKSTATICLIBTESTSHARED_EXPORT
#endif

#endif // LINKSTATICLIBTEST_GLOBAL_H
