#ifndef ADDSTATICLIBTEST_GLOBAL_H
#define ADDSTATICLIBTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef Q_OS_WIN
#if defined(ADDSTATICLIBTEST_LIBRARY)
#  define ADDSTATICLIBTESTSHARED_EXPORT Q_DECL_EXPORT
#elif defined(ADDSTATICLIBTEST_STATIC_LIBRARY)
#  define ADDSTATICLIBTESTSHARED_EXPORT
#else
#  define ADDSTATICLIBTESTSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#  define ADDSTATICLIBTESTSHARED_EXPORT
#endif

#endif // ADDSTATICLIBTEST_GLOBAL_H
